const stationSequences = {
  "Blue Line": [
    "Wimco Nagar Depot",
    "Wimco Nagar",
    "Tiruvottriyur",
    "Tiruvottriyur Theradi",
    "Kaladipet",
    "Tollgate",
    "New Washermanpet",
    "Tondiarpet",
    "Sir Theagaraya College",
    "Washermanpet",
    "Mannadi",
    "High Court",
    "Central Metro",
    "Government Estate",
    "LIC",
    "Thousand Lights",
    "AG-DMS",
    "Teynampet",
    "Nandanam",
    "Saidapet",
    "Little Mount",
    "Guindy",
    "Alandur",
    "Nanganallur Road",
    "Meenambakkam",
    "Chennai International Airport",
  ],
  "Green Line": [
    "Central Metro",
    "Egmore",
    "Nehru Park",
    "Kilpauk",
    "Pachaiyappa's College",
    "Shenoy Nagar",
    "Anna Nagar East",
    "Anna Nagar Tower",
    "Thirumangalam",
    "Koyambedu",
    "CMBT",
    "Arumbakkam",
    "Vadapalani",
    "Ashok Nagar",
    "Ekkattuthangal",
    "Alandur",
    "St. Thomas Mount",
  ],
  "Purple Line": [
    "Madhavaram Milk Colony",
    "Madhavaram Bus Terminus",
    "Venugopal Nagar",
    "Manjambakkam",
    "Madhavaram High Road",
    "Perambur",
    "Ayanavaram",
    "Purasaiwakkam High Road",
    "Kellys",
    "Chetpet",
    "Royapettah Government Hospital",
    "Thirumayilai",
    "Mandaiveli",
    "Greenways Road",
    "Adyar",
    "Indira Nagar",
    "Thiruvanmiyur",
    "Taramani Road Junction",
    "Perungudi",
    "Thoraipakkam",
    "Neelankarai",
    "Palavakkam",
    "Kottivakkam",
    "Thiruvanmiyur Depot",
    "Okkiyam Thoraipakkam",
    "Karapakkam",
    "Sholinganallur",
    "Sathyabama University",
    "Semmencherry",
    "SIPCOT 2",
  ],
  "Orange Line": [
    "Lighthouse",
    "Kutchery Road",
    "Alwarpet",
    "Nandanam",
    "Saidapet",
    "CIT Nagar",
    "Alaiamman Kovil",
    "Meenakshi College",
    "Kodambakkam",
    "Vadapalani",
    "Saligramam",
    "Koyambedu",
    "CMBT",
    "Mogappair",
    "Mannurpet",
    "Padi",
    "Thirumangalam",
    "Anna Nagar",
    "Villivakkam",
    "Kolathur",
    "Retteri",
    "Vinayagapuram",
    "Surapet",
    "Puzhal",
    "Red Hills",
    "Sholavaram",
    "Periyapalayam",
    "Avadi",
    "Thiruninravur",
    "Thiruvallur",
  ],
  "Red Line": [
    "Chennai Mofussil Bus Terminus (CMBT)",
    "Koyambedu",
    "Vadapalani",
    "Ashok Nagar",
    "Ekkattuthangal",
    "Alandur",
    "Nanganallur Road",
    "Meenambakkam",
    "Chennai International Airport",
    "Trident Hotel",
    "Pallavaram",
    "Chromepet",
    "Tambaram",
    "Perungalathur",
    "Vandalur",
    "Urapakkam",
    "Guduvanchery",
    "Potheri",
    "Maraimalai Nagar",
    "Singaperumal Koil",
    "Mahindra World City",
    "Chengalpattu",
  ],
};

export default stationSequences;
